import { ServiceProvider } from './service-card'

export const mockServiceProviders: ServiceProvider[] = [
  {
    id: '1',
    name: 'Mihai P.',
    profileImage: 'https://picsum.photos/200/200?random=1',
    rating: 4.8,
    reviewCount: 910,
    completedTasks: 1622,
    overallTasks: 2145,
    hourlyRate: 67.28,
    description:
      'I can fix a lot of things. I am very professional and have over 10 years of experience in pet care. I specialize in dog walking, training, and grooming. Your pets will be in safe hands!',
    specialties: ['Dog Walking', 'Pet Training', 'Pet Grooming'],
    hasVehicle: true,
    vehicleType: 'Transit Van',
    recentReview: {
      author: 'Lucy P.',
      date: 'Tue, Sep 30',
      text: 'He was incredibly knowledgeable and fast! Absolutely would work with him again.',
    },
  },
  {
    id: '2',
    name: 'Farshad S.',
    profileImage: 'https://picsum.photos/200/200?random=2',
    rating: 4.9,
    reviewCount: 455,
    completedTasks: 609,
    overallTasks: 823,
    hourlyRate: 70.27,
    description:
      '10 years experience with all types of pets. I offer professional pet grooming, sitting, and training services. I am patient, reliable, and love working with animals.',
    specialties: ['Pet Grooming', 'Pet Sitting', 'Pet Training'],
    isElite: true,
    recentReview: {
      author: 'Amelia G.',
      date: 'Sat, Jun 28',
      text: 'Excellent service! My dog looked amazing after the grooming session.',
    },
  },
  {
    id: '3',
    name: 'Sarah M.',
    profileImage: 'https://picsum.photos/200/200?random=3',
    rating: 4.7,
    reviewCount: 342,
    completedTasks: 487,
    overallTasks: 650,
    hourlyRate: 55.5,
    description:
      'Certified pet trainer with a passion for helping dogs and cats. I specialize in behavioral training, obedience, and socialization. Every pet deserves the best care!',
    specialties: ['Pet Training', 'Dog Walking', 'Behavioral Training'],
    hasVehicle: true,
    vehicleType: 'SUV',
    recentReview: {
      author: 'John D.',
      date: 'Mon, Sep 15',
      text: 'Sarah transformed our puppy! Highly recommend her training services.',
    },
  },
  {
    id: '4',
    name: 'Carlos R.',
    profileImage: 'https://picsum.photos/200/200?random=4',
    rating: 4.6,
    reviewCount: 289,
    completedTasks: 412,
    overallTasks: 556,
    hourlyRate: 48.99,
    description:
      'Professional dog walker and pet sitter. I offer flexible scheduling and can handle multiple pets at once. Your furry friends will get plenty of exercise and attention!',
    specialties: ['Dog Walking', 'Pet Sitting', 'Pet Exercise'],
    recentReview: {
      author: 'Maria L.',
      date: 'Thu, Sep 25',
      text: 'Carlos is fantastic! My dogs are always excited to see him.',
    },
  },
  {
    id: '5',
    name: 'Emily K.',
    profileImage: 'https://picsum.photos/200/200?random=5',
    rating: 4.9,
    reviewCount: 567,
    completedTasks: 789,
    overallTasks: 1024,
    hourlyRate: 72.5,
    description:
      'Veterinary assistant with extensive grooming experience. I provide top-quality grooming services including baths, haircuts, nail trimming, and more. Your pet will look and feel great!',
    specialties: ['Pet Grooming', 'Nail Care', 'Bath Services'],
    isElite: true,
    hasVehicle: true,
    vehicleType: 'Sedan',
    recentReview: {
      author: 'David H.',
      date: 'Wed, Sep 28',
      text: 'Emily is the best groomer we have ever used. So gentle and professional.',
    },
  },
  {
    id: '6',
    name: 'James T.',
    profileImage: 'https://picsum.photos/200/200?random=6',
    rating: 4.5,
    reviewCount: 198,
    completedTasks: 267,
    overallTasks: 345,
    hourlyRate: 42.0,
    description:
      'Experienced dog walker and pet lover. I offer daily walks, playtime, and basic training. I am reliable, punctual, and treat every pet like my own.',
    specialties: ['Dog Walking', 'Pet Sitting', 'Basic Training'],
    recentReview: {
      author: 'Sophie W.',
      date: 'Fri, Sep 20',
      text: 'James is wonderful! Always on time and our dog loves him.',
    },
  },
  {
    id: '7',
    name: 'Rachel B.',
    profileImage: 'https://picsum.photos/200/200?random=7',
    rating: 4.8,
    reviewCount: 423,
    completedTasks: 556,
    overallTasks: 723,
    hourlyRate: 65.0,
    description:
      'Certified animal behaviorist specializing in training and socialization. I work with dogs of all ages and breeds to improve behavior and obedience.',
    specialties: ['Pet Training', 'Behavioral Training', 'Socialization'],
    isElite: true,
    recentReview: {
      author: 'Michael P.',
      date: 'Sun, Sep 22',
      text: 'Rachel helped us with our rescue dog. Amazing progress in just weeks!',
    },
  },
  {
    id: '8',
    name: 'Tom H.',
    profileImage: 'https://picsum.photos/200/200?random=8',
    rating: 4.4,
    reviewCount: 156,
    completedTasks: 203,
    overallTasks: 278,
    hourlyRate: 38.5,
    description:
      'Pet sitting and dog walking services available. I am flexible with scheduling and can accommodate last-minute requests. Your pets will be in good hands!',
    specialties: ['Pet Sitting', 'Dog Walking', 'Pet Care'],
    hasVehicle: true,
    vehicleType: 'Hatchback',
    recentReview: {
      author: 'Anna M.',
      date: 'Tue, Sep 17',
      text: 'Tom took great care of our cat while we were away. Highly recommend!',
    },
  },
]

export const serviceCategories = [
  {
    id: 'dog-walking',
    name: 'Dog Walking',
    icon: '🐕',
    description: 'Professional dog walking services',
  },
  {
    id: 'pet-grooming',
    name: 'Pet Grooming',
    icon: '✂️',
    description: 'Complete grooming and styling services',
  },
  {
    id: 'pet-sitting',
    name: 'Pet Sitting',
    icon: '🏠',
    description: 'In-home pet sitting and care',
  },
  {
    id: 'pet-training',
    name: 'Pet Training',
    icon: '🎓',
    description: 'Professional training and behavior modification',
  },
  {
    id: 'vet-visit',
    name: 'Vet Visits',
    icon: '⚕️',
    description: 'Veterinary appointment assistance',
  },
  {
    id: 'pet-boarding',
    name: 'Pet Boarding',
    icon: '🛏️',
    description: 'Overnight pet boarding services',
  },
]
