FROM golang:1.25-alpine as builder

ENV GO111MODULE=on

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o server cmd/monolith/main.go

FROM scratch

WORKDIR /app

ENV ENV="prod"
#Gotta add all the env variables needed and defined in .env 

COPY --from=builder /app/server .

EXPOSE 3001

#ENTRYPOINT ["/app/cmd/api"]
ENTRYPOINT ["/app/server"]