FROM --platform=linux/amd64 chromedp/headless-shell:latest
RUN apt-get update --fix-missing && apt-get -y upgrade

ENTRYPOINT [ "/headless-shell/run.sh" ]
CMD ["--headless", "--disable-features=LazyFrameLoading", "--window-size=1920,1200","--disable-blink-features=AutomationControlled", "--disable-features=ScriptStreaming", "--no-process-per-site", "--disable-dev-shm-usage", "--disable-web-security", "--no-first-run", "--disable-setuid-sandbox", "--ignore-certificate-errors", "--no-zygote" ]