import NavBar from '@/components/nav-bar'
import { ThemeProvider } from '@/components/theme-provider'
import { Toaster } from '@/components/ui/sonner'
import clsx from 'clsx'
import type { Metadata } from 'next'
import '../globals.css'
import { fredoka, latto } from './(dashboard)/dashboard/fonts'
import InnerClientInit from './inner-client-init'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`antialiased` + clsx(latto.variable, fredoka.variable)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NavBar />
          <InnerClientInit>{children}</InnerClientInit>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  )
}
